spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockmarket
    username: broker
    password: KkN7{/uvw}?CKi).hDY8YSM0}YMC3QT
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
