spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockmarket
    username: vajgi90
    password: Vt901107
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
